# MMA Analytics ML Environment Configuration
# Python 3.11 with PyTorch CUDA support for RTX 3090
# Optimized for UFC fight analysis and video processing

name: mma-analytics
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  # Base Python
  - python=3.11
  - pip>=23.0

  # Core ML Framework (CUDA-enabled)
  - pytorch>=2.1.0
  - torchvision>=0.16.0
  - torchaudio>=2.1.0
  - pytorch-cuda=12.1  # CUDA 12.1 support for RTX 3090

  # Data Processing
  - pandas>=2.0.0
  - numpy>=1.24.0
  - scikit-learn>=1.3.0
  - scipy>=1.11.0
  - matplotlib>=3.7.0
  - seaborn>=0.12.0

  # Computer Vision & Video Processing
  - opencv>=4.8.0
  - ffmpeg>=6.0
  - imageio>=2.31.0
  - pillow>=10.0.0

  # Web Scraping & Data Collection
  - requests>=2.31.0
  - beautifulsoup4>=4.12.0
  - lxml>=4.9.0
  - html5lib>=1.1
  - selenium>=4.15.0

  # Development Tools
  - jupyter>=1.0.0
  - ipykernel>=6.25.0
  - ipython>=8.15.0
  - notebook>=7.0.0
  - pytest>=7.4.0
  - pytest-cov>=4.1.0
  - black>=23.7.0
  - flake8>=6.0.0
  - mypy>=1.5.0

  # Utilities & System
  - tqdm>=4.66.0
  - python-dotenv>=1.0.0
  - pyyaml>=6.0.1
  - tomli>=2.0.1
  - click>=8.1.0
  - rich>=13.5.0

  # Version Control & Large Files
  - git>=2.41.0
  - git-lfs>=3.2.0

  # Performance & GPU Monitoring
  - psutil>=5.9.0
  - gpustat>=1.1.0
  - nvitop>=1.3.0

  # Additional Python packages via pip
  - pip:
    # Video processing
    - ffmpeg-python>=0.2.0
    - moviepy>=1.0.3
    - decord>=0.6.0
    
    # Web scraping alternatives
    - playwright>=1.37.0
    - scrapy>=2.11.0
    
    # ML utilities
    - transformers>=4.33.0
    - datasets>=2.14.0
    - accelerate>=0.23.0
    
    # Data validation
    - pydantic>=2.3.0
    - jsonschema>=4.19.0
    
    # CLI utilities
    - typer>=0.9.0
    - questionary>=2.0.0
    
    # Testing utilities
    - pytest-mock>=3.11.0
    - pytest-asyncio>=0.21.0
    - pytest-xdist>=3.3.0
    
    # Documentation
    - mkdocs>=1.5.0
    - mkdocs-material>=9.3.0
    
    # Performance monitoring
    - memory-profiler>=0.61.0
    - line-profiler>=4.1.0

# Environment variables for GPU optimization
variables:
  # PyTorch settings
  PYTORCH_CUDA_ALLOC_CONF: "max_split_size_mb:512"
  CUDA_VISIBLE_DEVICES: "0"
  OMP_NUM_THREADS: "8"
  
  # Video processing settings
  FFMPEG_THREADS: "4"
  OPENCV_LOG_LEVEL: "ERROR"
  
  # Development settings
  PYTHONPATH: "${PYTHONPATH}:${PWD}/src"
  JUPYTER_CONFIG_DIR: "${PWD}/.jupyter"

# Platform-specific settings
# Uncomment for specific OS optimizations if needed
# platforms:
#   - linux-64
#   - win-64
#   - osx-64
#   - osx-arm64